# Generated by Django 3.2.20 on 2023-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0013_alter_articlecomments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='زمان انتشار'),
        ),
    ]
