# Generated by Django 3.2.20 on 2023-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0014_alter_article_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
    ]
