# Generated by Django 4.1.2 on 2023-04-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_pp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PP',
        ),
    ]
