# Generated by Django 3.2.20 on 2023-07-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_module', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart_module.order', verbose_name='سفارش'),
        ),
    ]
