# Generated by Django 4.2 on 2023-06-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='گالری محصولات')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='product_module.product')),
            ],
        ),
    ]
