# Generated by Django 3.2.20 on 2023-07-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری عکس محصول', 'verbose_name_plural': 'گالری عکس محصولات'},
        ),
    ]
