# Generated by Django 4.2 on 2023-06-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_productgallery_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
