# Generated by Django 3.2.20 on 2023-07-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='product_module.productbrand', verbose_name='برند محصول '),
        ),
    ]
