# Generated by Django 3.2.20 on 2023-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_auto_20230708_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='برند'),
            preserve_default=False,
        ),
    ]
