# Generated by Django 3.2.20 on 2023-07-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_productvisitcount_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvisitcount',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_visit', to='product_module.product', verbose_name='محصول '),
        ),
    ]
