# Generated by Django 4.2 on 2023-05-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0003_sliders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliders',
            name='image',
            field=models.ImageField(default='', upload_to='slider-images'),
            preserve_default=False,
        ),
    ]
