# Generated by Django 4.2 on 2023-05-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0004_sliders_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliders',
            old_name='slider_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='sliders',
            old_name='slider_title',
            new_name='url_title',
        ),
    ]
