# Generated by Django 4.2 on 2023-05-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0005_rename_slider_url_sliders_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='is_active',
            field=models.BooleanField(verbose_name='فعال / غیرفعال'),
        ),
    ]
