# Generated by Django 3.2.20 on 2023-07-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0006_alter_sliders_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک ')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('image', models.ImageField(upload_to='banner-images')),
                ('position', models.CharField(choices=[('product_list', 'صفحه ی لیست محصولات'), ('product_detail', 'صفحه ی جزییات محصولات'), ('home_page', 'خانه'), ('blog_page', 'صفحه ی مقالات'), ('blog_detail_page', 'صفحه ی جزییات مقالات'), ('about_us_page', 'درباره ما'), ('contact_us', 'ارتباط با ما'), ('user_panel', 'پنل کاربری')], max_length=300, verbose_name='موقعیت بنر های تبلیغاتی')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
