# Generated by Django 3.2.20 on 2023-07-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0007_sitebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list_top', 'بالای صفحه ی لیست محصولات'), ('product_list_right', 'سمت راست صفحه ی لیست محصولات'), ('product_detail', 'صفحه ی جزییات محصولات'), ('home_page', 'خانه'), ('blog_page', 'صفحه ی مقالات'), ('blog_detail_page', 'صفحه ی جزییات مقالات'), ('about_us_page', 'درباره ما'), ('contact_us', 'ارتباط با ما'), ('user_panel', 'پنل کاربری')], max_length=300, verbose_name='موقعیت بنر های تبلیغاتی'),
        ),
    ]
