# Generated by Django 4.2 on 2023-05-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0012_articlecomments_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomments',
            options={'verbose_name': ' کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='article_module.articlecomments', verbose_name='والد'),
        ),
    ]
